# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: shrestha
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: shrestha
      ME_CONFIG_MONGODB_URL: mongodb://admin:shrestha@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-db:
